### PR TITLE
LPS-112919 Add iframe support for KB

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
Hey @adolfopa and @martamedio, I have tested youtube and vimeo videos and they are still not working. 
I'm pasting here the original markup sent to the server and what is returning this: 

**Vimeo:**

`<div class="embed-responsive embed-responsive-16by9" data-embed-id="28612800" data-styles="{&quot;width&quot;:&quot;49%&quot;}" style="width:49%"><iframe allowfullscreen="" frameborder="0" height="315" mozallowfullscreen="" src="https://player.vimeo.com/video/28612800" webkitallowfullscreen="" width="560"></iframe></div>`


**returns**:
```
<div class="embed-responsive embed-responsive-16by9" style="width: 49.0%;">
<p>&nbsp;</p>
```

**Youtube**
`<div class="embed-responsive embed-responsive-16by9" data-embed-id="IWaC_hTumN8" data-styles="{&quot;width&quot;:&quot;49%&quot;}" style="width:49%"><iframe allow="autoplay; encrypted-media" allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/IWaC_hTumN8?rel=0" width="560"></iframe></div>`

**returns**
```
<div class="embed-responsive embed-responsive-16by9" style="width: 49.0%;">
<p>&nbsp;</p>

```

do you know waht could be missing in the sanitizer file?

**Comment by ambrinchaudhary** [comment]
FYI: these are the video cases we need to support: https://github.com/liferay/liferay-portal/blame/master/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/_diffs/plugins/videoembed/plugin.js#L268

**Comment by martamedio** [comment]
Please, see: https://github.com/ambrinchaudhary/liferay-portal/pull/369

**Pull request closed without merging**
