### PR TITLE
LPS-90052 Password sending via email and auto generation removal

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Thanks for that very helpful overview of before & after! Super clear 👍 

The functional changes you made all look good. I just SF'ed some.

New scenario
--
I found you were missing a scenario:

**4. When the user posts a comment as a guest, and clicks to activate their account afterwards:**
- New user receives a notification with a link where he can create his password. We cannot allow the user to specify a custom password in this flow because you need to verify that the user owns the email address linked to the posted comment(s).

Deprecation
--
> With this implementation, isSendPassword property could be deleted from Company Entity, but I'm not sure if this is possible as it affects the database model... What do you think about deleting it?

I've deprecated this method rather than delete it because 3rd party apps might be calling it. Now it always returns false. btw the method wasn't added by Service Builder in the first place so there is no database field for it.

Change to legacy template removal
--
I do still feel that we would severely annoy admins if we delete their carefully crafted & translated email templates without warning. So I've integrated the some code which we omitted in the backported tickets. If admins did not customize these legacy templates then no sign of them will appear on the UI, otherwise they appear as a readonly field and with the option to discard them when ready. I hope you like the approach.

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
@martamedio just realized I used the wrong ticket key in the last two commits

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
Merged: https://github.com/brianchandotcom/liferay-portal/pull/76862

**Pull request closed without merging**
