### PR TITLE
LPS-97485

### PR DESCRIPTION
**Pull request by topolik**
Hi Marta,

You are right, with your changes you only moved the problem from ModelPermissions into ModelPermissionFactory.

I tried to find & change all places where it's incorrectly used but there are so many places...
So I changed the idea and disallow reusing the model permissions (usually reused by ServiceContext). They would be used only for the first entity being created, which is usually the entity that user can see/access.

With this change the insecure API should no longer be insecure because reused ServiceContext should no more create guest/site-member permissions for entities deeper in the business logic.

Feel free to keep or remove the first 2 commits.

Note: let's wait for tests to see if I broke anything.

Thanks.

### CODE REVIEW

**Comment by topolik** [comment]
ci:test

**Comment by topolik** [comment]
ci:test 

Force pushed - fixed the NPE. Running tests again

**Comment by topolik** [comment]
ci:test

@martamedio, pushed the changes. Not sure how much would be broken. I'm thinking of two more things:
1, add tests for this case
2, workaround DocLib issue so that we can merge and create a bug ticket to fix it

**Comment by martamedio** [comment]
ci:test

**Comment by topolik** [comment]
ci:test

@martamedio - Removed the protection and cleaned the code to be merged. If the tests pass please peer review it, thank you.

**Comment by martamedio** [comment]
ci:test

**Comment by martamedio** [comment]
ci:stop

**Comment by topolik** [comment]
ci:test

**Comment by martamedio** [comment]
@topolik I'll review `CalendarFacetedSearcherTest.testBorrowedPermissions` 👀 , also fails locally and looks related

**Comment by topolik** [comment]
@martamedio 

Run @ localhost:
```
com.liferay.portal.search.facet.faceted.searcher.test.CalendarFacetedSearcherTest > testBorrowedPermissions STARTED

com.liferay.portal.search.facet.faceted.searcher.test.CalendarFacetedSearcherTest > testBorrowedPermissions PASSED
```

**Comment by martamedio** [comment]
@topolik test comparison fails locally for me 😕 

```
com.liferay.portal.search.facet.faceted.searcher.test.CalendarFacetedSearcherTest > testBorrowedPermissions STARTED

com.liferay.portal.search.facet.faceted.searcher.test.CalendarFacetedSearcherTest > testBorrowedPermissions FAILED
    org.junit.ComparisonFailure: {"from":0,"size":10000,"query":{"bool":{"must":[{"bool":{"must":[{"bool":{"should":[{"bool":{"must":[{"match":{"comments":{"query":"ePv5ULOL"}}}],"should":[{"match_phrase":{"comments":{"query":"ePv5ULOL","slop":50}}},{"match_phrase":{"comments":{"query":"ePv5ULOL","boost":2.0}}}]}},{"bool":{"must":[{"match":{"content":{"query":"ePv5ULOL"}}}],"should":[{"match_phrase":{"content":{"query":"ePv5ULOL","slop":50}}},{"match_phrase":{"content":{"query":"ePv5ULOL","boost":2.0}}}]}},{"bool":{"must":[{"match":{"description":{"query":"ePv5ULOL"}}}],"should":[{"match_phrase":{"description":{"query":"ePv5ULOL","slop":50}}},{"match_phrase":{"description":{"query":"ePv5ULOL","boost":2.0}}}]}},{"bool":{"should":[{"wildcard":{"properties":{"wildcard":"*epv5ulol*"}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"title":{"query":"ePv5ULOL"}}},{"match_phrase_prefix":{"title":{"query":"ePv5ULOL"}}}]}}],"should":[{"match_phrase":{"title":{"query":"ePv5ULOL","boost":2.0}}}]}},{"bool":{"should":[{"match_phrase":{"url":{"query":"ePv5ULOL"}}},{"bool":{"should":[{"wildcard":{"url":{"wildcard":"*epv5ulol*"}}}]}},{"match_phrase_prefix":{"url":{"query":"ePv5ULOL","max_expansions":300}}}]}},{"bool":{"should":[{"wildcard":{"userName":{"wildcard":"*epv5ulol*"}}}]}},{"bool":{"must":[{"match":{"assetCategoryTitles_en_US":{"query":"ePv5ULOL"}}}],"should":[{"match_phrase":{"assetCategoryTitles_en_US":{"query":"ePv5ULOL","slop":50}}},{"match_phrase":{"assetCategoryTitles_en_US":{"query":"ePv5ULOL","boost":2.0}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"assetTagNames_en_US":{"query":"ePv5ULOL"}}},{"match_phrase_prefix":{"assetTagNames_en_US":{"query":"ePv5ULOL"}}}]}}],"should":[{"match_phrase":{"assetTagNames_en_US":{"query":"ePv5ULOL","boost":2.0}}}]}},{"bool":{"must":[{"match":{"description_en_US":{"query":"ePv5ULOL"}}}],"should":[{"match_phrase":{"description_en_US":{"query":"ePv5ULOL","slop":50}}},{"match_phrase":{"description_en_US":{"query":"ePv5ULOL","boost":2.0}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"title_en_US":{"query":"ePv5ULOL"}}},{"match_phrase_prefix":{"title_en_US":{"query":"ePv5ULOL"}}}]}}],"should":[{"match_phrase":{"title_en_US":{"query":"ePv5ULOL","boost":2.0}}}]}}]}}]}}],"filter":[{"bool":{"must":[{"term":{"companyId":{"value":"20098"}}},{"bool":{"must":[{"terms":{"groupId":["37955"]}},{"terms":{"scopeGroupId":["37955"]}}]}},{"bool":{"should":[{"bool":{"must":[{"term":{"entryClassName":{"value":"com.liferay.calendar.model.CalendarBooking"}}},{"terms":{"status":["0"]}},{"terms":{"status":["0"]}},{"bool":{"should":[{"term":{"userId":{"value":"37976"}}},{"terms":{"groupRoleId":["37955-20115"]}},{"terms":{"roleId":["20115","20110","20107"]}},{"terms":{"sharedToUserId":["37976"]}},{"terms":{"roleIds":["20115","20110","20107"]}}]}}]}}]}}]}}]}},"explain":false,"stored_fields":"*","track_scores":true,"aggregations":{"userName":{"terms":{"field":"userName","size":10,"min_doc_count":1,"shard_min_doc_count":0,"show_term_doc_count_error":false,"order":[{"_count":"desc"},{"_key":"asc"}]}}}}->{entryClassPK=[37972], localized_title_sv_SE=[epv5ulol], groupId=[37955], publishDate=[19700101000000], createDate_sortable=[1593855098783], classNameId=[34017], localized_title_nl_NL=[epv5ulol], classPK=[37971], localized_title_zh_CN=[epv5ulol], scopeGroupId=[37955], modified=[20200704093138], localized_title_ar_SA_sortable=[epv5ulol], modified_sortable=[1593855098783], localized_title_pt_BR=[epv5ulol], localized_title_ca_ES_sortable=[epv5ulol], localized_title_zh_CN_sortable=[epv5ulol], localized_title_ca_ES=[epv5ulol], localized_title_hu_HU_sortable=[epv5ulol], visible=[true], localized_title_nl_NL_sortable=[epv5ulol], defaultLanguageId=[en_US], viewCount_sortable=[0], endTime_sortable=[1595438241331], priority=[0.0], viewActionId=[VIEW_BOOKING_DETAILS], companyId=[20098], localized_title_fr_FR=[epv5ulol], title_en_US=[ePv5ULOL], localized_title_hu_HU=[epv5ulol], status=[0], startTime_sortable=[1595434641331], localized_title_pt_BR_sortable=[epv5ulol], publishDate_sortable=[0], localized_title_fi_FI_sortable=[epv5ulol], relatedEntry=[true], uid=[com.liferay.calendar.model.CalendarBooking_PORTLET_37972], localized_title_de_DE_sortable=[epv5ulol], localized_title_en_US_sortable=[epv5ulol], groupRoleId=[37955-20115], localized_title_fr_FR_sortable=[epv5ulol], expirationDate_sortable=[9223372036854775807], startTime=[1595434641331], viewCount=[0], localized_title_sv_SE_sortable=[epv5ulol], localized_title_ja_JP=[epv5ulol], localized_title_fi_FI=[epv5ulol], createDate=[20200704093138], expirationDate=[99950812133000], localized_title_es_ES_sortable=[epv5ulol], entryClassName=[com.liferay.calendar.model.CalendarBooking], roleId=[20108], userName=[fejnk7h7 umtgqvdh], userId=[37959], localized_title_ja_JP_sortable=[epv5ulol], localized_title=[epv5ulol], stagingGroup=[false], localized_title_es_ES=[epv5ulol], localized_title_en_US=[epv5ulol], localized_title_ar_SA=[epv5ulol], calendarBookingId=[37972], endTime=[1595438241331], localized_title_de_DE=[epv5ulol]},{entryClassPK=[37986], localized_title_sv_SE=[epv5ulol], groupId=[37955], publishDate=[19700101000000], createDate_sortable=[1593855099828], classNameId=[34017], localized_title_nl_NL=[epv5ulol], classPK=[37985], localized_title_zh_CN=[epv5ulol], scopeGroupId=[37955], modified=[20200704093139], localized_title_ar_SA_sortable=[epv5ulol], modified_sortable=[1593855099828], localized_title_pt_BR=[epv5ulol], localized_title_ca_ES_sortable=[epv5ulol], localized_title_zh_CN_sortable=[epv5ulol], localized_title_ca_ES=[epv5ulol], localized_title_hu_HU_sortable=[epv5ulol], visible=[true], localized_title_nl_NL_sortable=[epv5ulol], defaultLanguageId=[en_US], viewCount_sortable=[0], endTime_sortable=[1594735785104], priority=[0.0], viewActionId=[VIEW_BOOKING_DETAILS], companyId=[20098], localized_title_fr_FR=[epv5ulol], title_en_US=[ePv5ULOL], localized_title_hu_HU=[epv5ulol], status=[0], startTime_sortable=[1594732185104], localized_title_pt_BR_sortable=[epv5ulol], publishDate_sortable=[0], localized_title_fi_FI_sortable=[epv5ulol], relatedEntry=[true], uid=[com.liferay.calendar.model.CalendarBooking_PORTLET_37986], localized_title_de_DE_sortable=[epv5ulol], localized_title_en_US_sortable=[epv5ulol], localized_title_fr_FR_sortable=[epv5ulol], expirationDate_sortable=[9223372036854775807], startTime=[1594732185104], viewCount=[0], localized_title_sv_SE_sortable=[epv5ulol], localized_title_ja_JP=[epv5ulol], localized_title_fi_FI=[epv5ulol], createDate=[20200704093139], expirationDate=[99950812133000], localized_title_es_ES_sortable=[epv5ulol], entryClassName=[com.liferay.calendar.model.CalendarBooking], roleId=[20108], userName=[cgvdmpjy 7jhp8bau], userId=[37976], localized_title_ja_JP_sortable=[epv5ulol], localized_title=[epv5ulol], stagingGroup=[false], localized_title_es_ES=[epv5ulol], localized_title_en_US=[epv5ulol], localized_title_ar_SA=[epv5ulol], calendarBookingId=[37986], endTime=[1594735785104], localized_title_de_DE=[epv5ulol]}->{cgvdmpjy 7jhp8bau=1, fejnk7h7 umtgqvdh=1} expected:<[cgvdmpjy 7jhp8bau=1[]]> but was:<[cgvdmpjy 7jhp8bau=1[, fejnk7h7 umtgqvdh=1]]>
    	at org.junit.Assert.assertEquals(Assert.java:115)
    	at com.liferay.portal.search.test.util.AssertUtils.assertEquals(AssertUtils.java:100)
    	at com.liferay.portal.search.test.util.AssertUtils.assertEquals(AssertUtils.java:88)
    	at com.liferay.portal.search.test.util.AssertUtils.assertEquals(AssertUtils.java:60)
    	at com.liferay.portal.search.test.util.FacetsAssert.assertFrequencies(FacetsAssert.java:67)
    	at com.liferay.portal.search.facet.faceted.searcher.test.CalendarFacetedSearcherTest.testBorrowedPermissions(CalendarFacetedSearcherTest.java:117)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$2.evaluate(TestExecutorRunnable.java:234)
    	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:143)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:181)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
    	at java.lang.Thread.run(Thread.java:748)

1 test completed, 1 failed
```

**Comment by topolik** [comment]
I have master from last week, might be related

Dne so 4. 7. 2020 11:37 uživatel Marta Medio <notifications@github.com>
napsal:

**Comment by martamedio** [comment]
Hey @topolik 
I've been exploring this changes during the past week and `com.liferay.portal.search.facet.faceted.searcher.test.CalendarFacetedSearcherTest` no longer fails locally after rebasing, I think it was unrelated to our changes.
I'm going to relaunch for the last time to see if there have been any other failures but I think this is ready to merge.

**Comment by martamedio** [comment]
ci:test

**Comment by martamedio** [comment]
Still failing (also locally), my fault during on the rebasing process 🤦‍♀️

**Comment by topolik** [comment]
ci:test

**Comment by martamedio** [comment]
@topolik I analyzed the results of the last test execution:

**1. [test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/147](https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/300497/)**
There are 7 tests failing, in all of them the problem it's an error with the session in the testing machine during the execution:

```
org.openqa.selenium.SessionNotCreatedException: session not created exception
from disconnected: unable to connect to renderer
  (Session info: chrome=65.0.3325.162)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 4.14.138-rancher x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 307 milliseconds
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'cloud-10-0-19-199.lax.liferay.com', ip: '172.19.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.138-rancher', java.version: '1.8.0_121'
Driver info: driver.version: ChromeDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	...

```

**2. [test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/38](https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/406555/)**
`LocalFile.WorkflowMetrics#ViewTopAsigneePerformance` is failling, I've run it locally using Poshi and it looks like they're trying to launch a process with Groovy that has some problem and that's why it's nor finding the expecting element:
```
2020-07-15 11:28:41.945 ERROR [http-nio-8080-exec-9][EditServerMVCActionCommand:542] SanitizerLogWrapper warning: Following message contains CRLF characters
startup failed:
Script1.groovy: 11: expecting EOF, found ')' @ line 11, column 67.
   l.util.PortalUtil.getCompanyId)actionReq
```
I'm surprised it's not failing upstream 🤔 

**3. [test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8](https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/437069/)**
`com.liferay.sharing.blogs.internal.test.BlogsEntrySharingTest.testUserWithUpdateAndViewSharingEntryActionCannotAddDiscussionPrivateModel` is failing due to a timeout during execution:

```
java.lang.RuntimeException: java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-0 [ACTIVE]
	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.index.CreateIndexRequestExecutorImpl.getCreateIndexResponse(CreateIndexRequestExecutorImpl.java:98)
```

Works locally without errors:

```
com.liferay.sharing.blogs.internal.test.BlogsEntrySharingTest > testUserWithUpdateAndViewSharingEntryActionCannotAddDiscussionPrivateModel STARTED
com.liferay.sharing.blogs.internal.test.BlogsEntrySharingTest > testUserWithUpdateAndViewSharingEntryActionCannotAddDiscussionPrivateModel PASSED
```

Nothing seems to be related to our permission changes.

**Comment by topolik** [comment]
ci:forward

**Pull request closed without merging**
