### PR TITLE
LPS-99075 Need to use original context path in LastPath, this is a bu…

### PR DESCRIPTION
**Pull request by tinatian**
…g introduced by LPS-68241(ad5a20740e4b59865d62b32d7b91a94e7cb42718)

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
Hi @martamedio,
Could you please verify if this fixed the issue?

Thanks.
Tina

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
@tinatian Thank you so much! Works perfectly 😃 

Please, see: https://github.com/brianchandotcom/liferay-portal/pull/76674

**Comment by martamedio** [comment]
Merged: https://github.com/brianchandotcom/liferay-portal/pull/76674

**Pull request closed without merging**
