### PR TITLE
LPS-115899 Email obfuscation

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Marta. I've added email obfuscation logic. As I mentioned earlier, I feel we should as minimum mask 3 characters because 26^3 equals 17,576 combinations whereas 26^2 equals 676 only. (I'm assuming alphabetic characters only in the example). For email addresses shorter than 3 characters before '@', I don't think these people care much about guess-ability!

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
LGTM, thank you @stian-sigvartsen 👏

**Comment by martamedio** [comment]
ci:forward

**Comment by martamedio** [comment]
Rebased: https://github.com/martamedio/liferay-portal/pull/166

**Pull request closed without merging**
