### PR TITLE
OAUTH2-275 Expand panels that contain assigned scopes upon page load

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Marta. I think this would be a good UX improvement. But maybe not worth it if it will break a lot of Poshi tests. Let's see what CI thinks.

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
The failures look unrelated

**Comment by xbrianlee** [comment]
ci:test:bundle

**Comment by xbrianlee** [comment]
ci:test:oauth2

**Comment by stian-sigvartsen** [comment]
Closing. See https://github.com/stian-sigvartsen/liferay-portal/pull/156#issuecomment-490541060

**Pull request closed without merging**
