### PR TITLE
LPS-117309 Fix regression in logging

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Following on from martamedio/liferay-portal/pull/182.

Avoids logging at error level, except when encountering likely system configuration or integration issues. For example 
* Missing SAML attribute mappings
* Portal instance is configured to disallow strangers from creating accounts with the company MX + Resolved user has company MX. This usually means some LDAP integration should have imported the user already. It could be a malicious attempt to create an account, but sys admin would likely want to be alerted to this as an ERROR also.

Other rejected stranger access is not logged unless at DEBUG level, because it is too likely this will happen and could DoS logs.

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:abort

**Comment by stian-sigvartsen** [comment]
ci:stop

**Comment by stian-sigvartsen** [comment]
@martamedio I rebased on top of martamedio/liferay-portal/pull/184 and force pushed because I realized there would be a conflict between the two PRs otherwise.

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:forward

**Pull request closed without merging**
