### PR TITLE
LPS-106919 Allow matching of root resources with wildcard

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
This fixes the regression detailed in [LPS-106919](https://issues.liferay.com/browse/LPS-106919).

I also include 5d20520dd which is to re-instate the fix for [LPS-102770](https://issues.liferay.com/browse/LPS-102770) which was reverted upstream because of the aforementioned regression it caused.

Additionally I include a suite of tests for LPS-102770 with 6555fc2

/cc  @csierra

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83609. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
