### PR TITLE
LPS-123910 Use Meta.Type.Password for proxyPassword.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Hello @marianoalvarosaiz 

Can you please send this to liferay-lima? As far as we know the S3 store integration belongs to them.

Thanks!

**Comment by lipusz** [comment]
ci:close

**Comment by lipusz** [comment]
Or to Core Infra.

**Pull request closed without merging**
