### PR TITLE
LPS-101720 | LPS-102019 | LPS-102476 | LPS-102477 | LPS-104519 | LPS-104662

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by martamedio** [comment]
Please, see: https://github.com/arthurchan35/liferay-portal/pull/37

**Pull request closed without merging**
